[package]
name = "udp-over-tcp"
version = "0.1.0"
authors = ["Mullvad VPN"]
description = "Tunnel UDP traffic inside a TCP stream"
edition = "2018"
publish = false

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[dependencies]
tokio = { version = "0.2.22", features = ["rt-threaded", "macros", "tcp", "udp", "io-util"] }
err-context = "0.1.0"
log = "0.4.11"
env_logger = "0.7.1"
futures = "0.3.5"
structopt = "0.3.16"
